// Timing backbone. All beat/word/event times come from public/timing.json,
// generated by pipeline/tts.py from the actual synthesized VO audio.
import timingData from "../public/timing.json";

export const FPS = 30;

export type WordTiming = { text: string; startMs: number; endMs: number };
export type ChunkTiming = {
  id: string;
  startMs: number;
  endMs: number;
  words: WordTiming[];
};
export type BeatTiming = {
  id: string;
  startMs: number;
  endMs: number;
  chunks: ChunkTiming[];
};
export type Timing = {
  totalMs: number;
  beats: BeatTiming[];
  events: Record<string, number>;
};

export const TIMING = timingData as Timing;

export const msToFrame = (ms: number): number => Math.round((ms / 1000) * FPS);

/** Absolute frame of a named event (e.g. "b1.generals"). */
export const ev = (name: string): number => {
  const ms = TIMING.events[name];
  if (ms === undefined) {
    throw new Error(`Unknown timing event: ${name}`);
  }
  return msToFrame(ms);
};

export const beat = (id: string): BeatTiming => {
  const b = TIMING.beats.find((x) => x.id === id);
  if (!b) throw new Error(`Unknown beat: ${id}`);
  return b;
};

export const beatFrames = (id: string): { from: number; to: number } => {
  const b = beat(id);
  return { from: msToFrame(b.startMs), to: msToFrame(b.endMs) };
};

export const TOTAL_FRAMES = msToFrame(TIMING.totalMs);
