#!/usr/bin/env node
// Regenerate src/game/art/glbdata.js — the hero-tree GLBs as data URIs.
//
// Why inline at all: a published artifact runs under a CSP that blocks every
// request to another host or path, so a .glb fetched by URL 404s. The hero-tree
// loader treats a missing model as "use the procedural trunks", which is the
// right behaviour for a missing asset and the wrong behaviour for a blocked
// one — the world silently lost its hero trees with no error anywhere. Inlining
// removes the failure mode rather than handling it.
//
// Run after `npm run assets` regenerates the Blender output.
// Usage: node scripts/inlineglb.mjs
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const dir = resolve(root, 'public/assets/models/trees')
const files = readdirSync(dir).filter((f) => f.endsWith('.glb')).sort()
let total = 0
const lines = [
  '// GENERATED by scripts/inlineglb.mjs — do not edit by hand.',
  '// Hero trees as data URIs so the game ships as a single self-contained file;',
  '// see that script for why a URL fetch is not good enough.',
  'export const GLB = {',
]
for (const f of files) {
  const b = readFileSync(resolve(dir, f))
  total += b.length
  lines.push(`  '${f}': 'data:model/gltf-binary;base64,${b.toString('base64')}',`)
}
lines.push('}')
writeFileSync(resolve(root, 'src/game/art/glbdata.js'), lines.join('\n') + '\n')
console.log(`inlined ${files.length} models, ${Math.round(total / 1024)}KB raw`)
